version: "3.9"
services:
  ocr:
    build:
      context: .
      dockerfile: "Dockerfile"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    runtime: nvidia
    ports: 
      - 5002:5002
    volumes: 
      - .:/app
    working_dir: /app
    command: ["python3", "main.py"]
