version: "3.9"
services:
  ocr:
    build:
      context: .
      dockerfile: "Dockerfile.amd64"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports: 
      - 5002:5002
    volumes: 
      - .:/app
    working_dir: /app
    command: ["python3", "main.py"]
